# Generated by Django 5.2.5 on 2026-03-08 06:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Goat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag_number', models.CharField(max_length=50, unique=True)),
                ('gender', models.CharField(max_length=10)),
                ('date_of_birth', models.DateField()),
                ('weight', models.FloatField()),
                ('health_status', models.CharField(max_length=100)),
                ('date_added', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
