# Generated by Django 5.2.5 on 2026-03-08 07:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goats', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='goat',
            name='date_bought',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='goat',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='goat_images/'),
        ),
        migrations.AddField(
            model_name='goat',
            name='is_alive',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='goat',
            name='mother',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='kids', to='goats.goat'),
        ),
        migrations.AddField(
            model_name='goat',
            name='purchase_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='goat',
            name='date_of_birth',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='goat',
            name='gender',
            field=models.CharField(choices=[('M', 'Male'), ('F', 'Female')], max_length=1),
        ),
        migrations.CreateModel(
            name='DeathRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_of_death', models.DateField()),
                ('cause', models.TextField(blank=True)),
                ('goat', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='goats.goat')),
            ],
        ),
        migrations.CreateModel(
            name='SaleRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_sold', models.DateField()),
                ('sale_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('goat', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='goats.goat')),
            ],
        ),
    ]
