# Generated by Django 5.2.5 on 2026-03-15 07:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('goats', '0002_goat_date_bought_goat_image_goat_is_alive_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='goat',
            name='weight',
        ),
    ]
