# Generated by Django 5.2.5 on 2026-03-15 07:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goats', '0003_remove_goat_weight'),
    ]

    operations = [
        migrations.AddField(
            model_name='goat',
            name='is_sold',
            field=models.BooleanField(default=False),
        ),
    ]
