# Generated by Django 5.2.5 on 2026-03-21 05:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goats', '0004_goat_is_sold'),
    ]

    operations = [
        migrations.AddField(
            model_name='goat',
            name='status',
            field=models.CharField(choices=[('alive', 'Alive'), ('sold', 'Sold'), ('dead', 'Dead')], default='alive', max_length=10),
        ),
    ]
