# Generated by Django 5.2.5 on 2026-03-21 06:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('goats', '0005_goat_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='goat',
            name='is_alive',
        ),
        migrations.RemoveField(
            model_name='goat',
            name='is_sold',
        ),
    ]
